export const INVARIANTS = {
  MODE_RESTRICTION: "INV-001",
  AUDIT_REQUIRED: "INV-002",
  CONFIRMATION_REQUIRED: "INV-003",
  SCHEMA_VALIDATION: "INV-004",
  PROTECTED_PATH: "INV-005",
  CAPABILITY_GRANT_REQUIRED: "INV-006",
  TASK_LOCK_REQUIRED: "INV-007",
  PLAN_COMMIT_MATCH: "INV-008",
  APPROVAL_REQUIRED: "INV-009"
} as const;

export type InvariantId =
  typeof INVARIANTS[keyof typeof INVARIANTS];
